#version: "1.9"


javacont:
 build: ./java
 tty: true

jenkinscont:
 build: ./jenkins
 links:
  - javacont
 ports:
  - 8080:8080
 tty: true

jiracont:
 build: ./jira
 links:
  - javacont
 ports:
  - 8089:8080
 tty: true

nexuscont:
 build: ./nexus
 links:
  - javacont
 ports:
  - 8081:8081
 tty: true

tomcatcont:
 build: ./tomcat
 links:
  - javacont
 ports:
  - 8083:8080
 tty: true
 
zabbixcont: 
 build: ./zabbix
 links:
  - javacont
 ports:
  - 80:80
 tty: true
