#version: "1.9"


javaFile:
 build: ./java
 tty: true

jenkinsFile:
 build: ./jenkins
 ports:
  - 8080:8080
 tty: true
	
jiraFile:
 build: ./jira
 ports:
  - 8089:8089
 tty: true
	
nexusFile:
 build: ./nexus
 ports:
  - 8081:8081
 tty: true
	
tomcatFile:
 build: ./tomcat
 ports:
  - 8083:8080
 tty: true
	
zabbixFile: 
 build: ./zabbix
 ports:
  - 8084:80
 tty: true
	
	
	